#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := project_template
EXTRA_COMPONENT_DIRS = $(PROJECT_PATH)/../components
# SDKCONFIG := $(PROJECT_PATH)/../sdkconfig

include $(IDF_PATH)/make/project.mk

